.TH "C:/Users/aabha/OneDrive/Desktop/M2_Smart_Advertisement_Board-main Directory Reference" 3 "Sat Apr 23 2022" "Version 1.0.0" "M2_Smart_Advertisement_Board" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/aabha/OneDrive/Desktop/M2_Smart_Advertisement_Board-main Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fB0\-Abstrat\fP"
.br
.ti -1c
.RI "directory \fB1\-Requirments\fP"
.br
.ti -1c
.RI "directory \fB3\-Implimentation\fP"
.br
.ti -1c
.RI "directory \fB4\-Test_case\fP"
.br
.ti -1c
.RI "directory \fB5\-Report\fP"
.br
.ti -1c
.RI "directory \fB6\-Output\fP"
.br
.in -1c
