.TH "C:/Users/aabha/OneDrive/Desktop/M2_Smart_Advertisement_Board-main/3-Implimentation Directory Reference" 3 "Sat Apr 23 2022" "Version 1.0.0" "M2_Smart_Advertisement_Board" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/aabha/OneDrive/Desktop/M2_Smart_Advertisement_Board-main/3-Implimentation Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBBuild\fP"
.br
.ti -1c
.RI "directory \fBdocumentation\fP"
.br
.ti -1c
.RI "directory \fBinc\fP"
.br
.ti -1c
.RI "directory \fBMAKE FILES\fP"
.br
.ti -1c
.RI "directory \fBsrc\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.in -1c
