.TH "C:/Users/aabha/OneDrive/Desktop/M2_Smart_Advertisement_Board-main/3-Implimentation/main.c" 3 "Sat Apr 23 2022" "Version 1.0.0" "M2_Smart_Advertisement_Board" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/aabha/OneDrive/Desktop/M2_Smart_Advertisement_Board-main/3-Implimentation/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <xc\&.h>\fP
.br
\fC#include <avr/io\&.h>\fP
.br
\fC#include <util/delay\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBF_CPU\fP   16000000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define F_CPU   16000000"

.PP
Definition at line \fB8\fP of file \fBmain\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line \fB12\fP of file \fBmain\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for M2_Smart_Advertisement_Board from the source code\&.
