.TH "C:/Users/aabha/OneDrive/Desktop/M2_Smart_Advertisement_Board-main/3-Implimentation/MAKE FILES/main.d" 3 "Sat Apr 23 2022" "Version 1.0.0" "M2_Smart_Advertisement_Board" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/aabha/OneDrive/Desktop/M2_Smart_Advertisement_Board-main/3-Implimentation/MAKE FILES/main.d
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for M2_Smart_Advertisement_Board from the source code\&.
