.TH "md__c___users_aabha__one_drive__desktop__m2__smart__advertisement__board_main_4__test_case__t_e_s_t__p_l_a_n__r_e_a_d_m_e" 3 "Sat Apr 23 2022" "Version 1.0.0" "M2_Smart_Advertisement_Board" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c___users_aabha__one_drive__desktop__m2__smart__advertisement__board_main_4__test_case__t_e_s_t__p_l_a_n__r_e_a_d_m_e \- The Test plan of this project is 
1\&.To know the importnace of the project\&.
.PP
2\&.To know the work in specific conditions\&.
.PP
3\&.Working Principle and architecture of the simulide\&.
.PP
4\&.To verify the microcontroller chip\&. 
.SH "Test Cases"
.PP
.SS "Folder structure"
SL\&. NO\&.   Description   Test cases    1   DC motor   passed    2   Audio out   passed    3   LED's   passed    4   voltage source   passed   
