.TH "md__c___users_aabha__one_drive__desktop__m2__smart__advertisement__board_main_5__report__r_e_a_d_m_e" 3 "Sat Apr 23 2022" "Version 1.0.0" "M2_Smart_Advertisement_Board" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c___users_aabha__one_drive__desktop__m2__smart__advertisement__board_main_5__report__r_e_a_d_m_e \- OBJECTIVE OF THIS PROJECT 
An Avertisement board is for attracting the people around us and also to make aware of our porduct\&. Advertising board\&. An advertising board, or A-board, is usually a term reserved for the advertising hoardings seen at association football matches, although there are other more general forms such as billboards and posters\&. 
.SH "INTRODUCTION"
.PP
With the help of this project we can advertise our products, as comparied to an conventional led board it will conusme less power and its fully automated inaddition to that it can easy be replaced when needed\&. we can advertise or make people aware of the sourounds or even Govternment can use it introduce new scheme and make mass educated form the same\&. The advertising design is the artwork that is visual and created for advertisements specifically\&. Graphic design has become synonymous with the world of advertising, and visual representations of products and services are essential for any brand to get its message across to the public\&. Advertising has three primary objectives: to inform, to persuade, and to remind\&. Informative Advertising creates awareness of brands, products, services, and ideas\&. 
.SH "COMPONENTS AND SUPPLIES"
.PP
1\&.ATmega328p
.PP
2\&.LED bulb and LED strip
.PP
3\&.Connecting Wires
.PP
4\&.Audio out
.PP
5\&.10 V voltage source
.PP
6\&.DC motor
.PP
7\&.Advertisement board
.PP
8\&.Banner with advertisement in rolled format\&.
.SH "ADVANTAGES"
.PP
1\&.A advertisement board help people and company to advertise there porducts and ideas to the masses\&.
.PP
2\&.Govternment can also use this technology to introduce new schemes to the people\&.
.SH "4W & H  (WHO,WHAT,WHEN,WHERE,HOW)"
.PP
.SS "WHO"
A ADVERTISEMENT BOARD IS USED TO ADVERTISE NEW PRODUCTS AND IDEAS AND ALSO ATTRACT PROPLE\&. 
.SS "WHAT"
HIGH RELIABILITY\&. 
.SS "WHEN"
IT CAN BE USED ANY TIME MOSTLY\&. 
.SS "WHERE"
ANYWARE WHERE PEOPLE CAN SEE\&. 
.SS "HOW"
EASY TO USE AND ADJUSTED IN A IN CROUDED AREAS\&.
.SH "SWOT(STRENGTH,WEAKNESS,OPPORTUNITY,THREATS)"
.PP
.SS "STRENGTH"
1\&.IT IS LESS IN PRICE\&.
.PP
2\&.HELPS IN EDUCATING PEOPLE
.PP
3\&.WE CAN CHOOSE ADVERTISEMENT OR LED TO ACTIVATE\&. 
.SS "WEAKNESS"
CAN BE LESS POWEFULL IN CLOUDY WEATHER 
.SS "OPPORTUNITY"
INTERNET OF THINGS(IOT) 
.SS "THREATS"
CAN BE EASYLY BROKEN 
.SH "Components and Software required"
.PP
1\&.\fCAtmega28p\fP - A single-chip microcontroller created by Atmel in the megaAVR family
.PP
2\&.\fCSimulIDE\fP - A simple real time electronic circuit simulator
.PP
3\&.\fCVS Code\fP - Visual Studio Code is a code editor redefined and optimized for building and debugging modern web and cloud applications
.PP
4\&.[LED]() - A light-emitting diode (LED) is a semiconductor light source that emits light when current flows through it
.PP
5\&.\fCAtmel Studio\fP - The Atmel Studio 7 IDP gives you a seamless and easy-to-use environment to write, build, and debug your applications written in C/C++ or assembly code\&. It also connects seamlessly to the debuggers, programmers, and development kits that support AVR\&.
.PP
6\&.[DC Motor]() - A DC motor is any of a class of rotary electrical motors that converts direct current electrical energy into mechanical energy\&. 
.SH "Applications"
.PP
1\&.Billboard advertisements are designed to catch a person's attention and create a memorable impression very quickly, leaving the reader thinking about the advertisement after they have driven past it\&. They have to be readable in a very short time because they are usually read while being passed at high speeds\&.
.PP
2\&.The advertising design is the artwork that is visual and created for advertisements specifically\&. Graphic design has become synonymous with the world of advertising, and visual representations of products and services are essential for any brand to get its message across to the public
.PP
3\&.Can be placed anyware Advertising billboards are placed strategically along major thoroughfares and highways, thus, increasing the possibilities of being seen by a great number of consumers all throughout the day\&.
.PP
4\&.Access to Targeted Audience since billboards can be placed in areas chosen by advertisers or companies, it will be easier for these companies to reach a particular or specific consumer group they sell their services and products to 
.SH "Implementation Block Diagram"
.PP
 
.SH "In Action"
.PP
ON   OFF          
.SH "Working and Simulation"
.PP
 
.SH "THANK YOU"
.PP

