.TH "md__c___users_aabha__one_drive__desktop__m2__smart__advertisement__board_main_1__requirments__r_e_a_d_m_e" 3 "Sat Apr 23 2022" "Version 1.0.0" "M2_Smart_Advertisement_Board" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c___users_aabha__one_drive__desktop__m2__smart__advertisement__board_main_1__requirments__r_e_a_d_m_e \- Details requirements 

.SH "High level Requirements"
.PP
ID   Description   Status    HLR1   Atmega328   Microcontroller used for the process    HLR2   DC Motor   To chnge the advertisement    HLR3   Volt\&. Source   Power source   
.SH "Low level Requirements"
.PP
ID   Description   Status    LLR1   Audio out   advertisement sound    LLR2   Led's   For Alternative Blinking   
